package com.eventflow.platform.exception;

public enum ErrorCode {
    VALIDATION_ERROR,
    UNAUTHORIZED,
    FORBIDDEN,
    RESOURCE_NOT_FOUND,
    EMAIL_ALREADY_EXISTS,
    INVALID_CREDENTIALS,
    EVENT_NOT_BOOKABLE,
    ALREADY_REGISTERED,
    BOOKING_NOT_FOUND,
    OPTIMISTIC_LOCK_CONFLICT,
    INTERNAL_SERVER_ERROR
}
